package com.pizzaapp.PizzaWebApp.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import java.util.HashMap;
import java.util.Map;
import java.util.Collections;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Document(collection = "menu_items")
public class MenuItem {

    @Id
    private String id;
    private String name;
    private String description;
    private String imageUrl;
    private String category;
    private boolean available = true;
    private boolean veg=true;

    // 🔴 RESTORED: This acts as the "Base Price" or "Display Price"
    private double price;

    // 🟢 NEW: Holds specific sizes (Small=199, Medium=399)
    private Map<String, Double> sizes = new HashMap<>();

    // --- SMART GETTER FOR PRICE ---
    // If 'price' is 0, try to find the cheapest size to show as the "Starts at" price
    public double getPrice() {
        if (price > 0) return price;
        if (!sizes.isEmpty()) {
            return Collections.min(sizes.values());
        }
        return 0.0;
    }

    // Explicit setter is generated by @Data, but you can add it manually if needed:
    public void setPrice(double price) {
        this.price = price;
    }

    public boolean isVeg() { return veg; }
    public void setVeg(boolean veg) { this.veg = veg; }

    public boolean getVeg() {
        return this.veg;
    }

}