spring.application.name=PizzaWebApp
# Server configuration
server.port=8080

# Optional — Logging SQL Queries
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=true

#mongodb url
spring.data.mongodb.uri=${MONGODB_URI}
# Email Configuration
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true



# 1. See exactly which Controller method is being called
#logging.level.org.springframework.web=DEBUG

# 2. See the actual data being sent/received from MongoDB
#logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

# 3. Check if Spring Security is blocking your POST request (CSRF issues)
#logging.level.org.springframework.security=DEBUG

# 4. See the values being passed in your @RequestParam and @PostMapping
#logging.level.org.apache.catalina.core.ContainerBase.[Tomcat].[localhost]=DEBUG


#jwt properties
jwt.secret=${JWT_SECRET}
jwt.access-expiration=900000
jwt.refresh-expiration=2592000000

spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false